create table sales
(
    sold_date date,
    sold_time integer,
    shipped_date date,
    item_sk int4 not null,
    bill_customer_sk int4 ,
    bill_salutation char(10) ,
    bill_first_name char(20) ,
    bill_last_name char(30) ,
    bill_birth_day int4 ,
    bill_birth_month int4 ,
    bill_birth_year int4 ,
    bill_birth_country varchar(20) ,
    bill_login char(13) ,
    bill_email_address char(50) ,
    bill_gender char(1) ,
    bill_marital_status char(1) ,
    bill_education_status char(20) ,
    bill_purchase_estimate int4 ,
    bill_credit_rating char(10) ,
    bill_dep_count int4 ,
    bill_dep_employed_count int4 ,
    bill_dep_college_count int4,
    bill_income_band_sk         integer                       ,
    bill_buy_potential          char(15)                      ,
    bill_hd_dep_count              integer                       ,
    bill_vehicle_count          integer                       ,
    bill_street_number char(10) ,
    bill_street_name varchar(60) ,
    bill_street_type char(15) ,
    bill_suite_number char(10) ,
    bill_city varchar(60) ,
    bill_county varchar(30) ,
    bill_state char(2) ,
    bill_zip char(10) ,
    bill_country varchar(20) ,
    bill_gmt_offset numeric(5,2) ,
    bill_location_type char(20),
    ship_customer_sk int4,
    ship_salutation char(10) ,
    ship_first_name char(20) ,
    ship_last_name char(30) ,
    ship_birth_day int4 ,
    ship_birth_month int4 ,
    ship_birth_year int4 ,
    ship_birth_country varchar(20) ,
    ship_login char(13) ,
    ship_email_address char(50) ,
    ship_gender char(1) ,
    ship_marital_status char(1) ,
    ship_education_status char(20) ,
    ship_purchase_estimate int4 ,
    ship_credit_rating char(10) ,
    ship_dep_count int4 ,
    ship_dep_employed_count int4 ,
    ship_dep_college_count int4,
    ship_income_band_sk         integer                       ,
    ship_buy_potential          char(15)                      ,
    ship_hd_dep_count              integer                       ,
    ship_vehicle_count          integer                       ,
    ship_street_number char(10) ,
    ship_street_name varchar(60) ,
    ship_street_type char(15) ,
    ship_suite_number char(10) ,
    ship_city varchar(60) ,
    ship_county varchar(30) ,
    ship_state char(2) ,
    ship_zip char(10) ,
    ship_country varchar(20) ,
    ship_gmt_offset numeric(5,2) ,
    ship_location_type char(20),
    outlet_sk int4 ,
    location_sk int4,
    ship_mode_sk int4,
    warehouse_sk int4,
    promo_sk int4 ,
    order_number int8 not null,
    quantity int4 ,
    wholesale_cost numeric(7,2) ,
    list_price numeric(7,2) ,
    sales_price numeric(7,2) ,
    ext_sales_price numeric(7,2) ,
    ext_discount_amt numeric(7,2) ,
    ext_wholesale_coast numeric(7,2) , /* Made a typo */
    ext_tax numeric(7,2) ,
    coupon_amt numeric(7,2),
    ship_cost numeric(7,2),
    net_paid numeric(7,2) ,
    net_profit numeric(7,2),
    channel char(10)
  ,primary key (item_sk, channel, order_number)
) distkey(item_sk) sortkey(sold_date);

